# Generated by Django 4.2.23 on 2025-07-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0002_alter_course_level_alter_studentprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
