# Generated by Django 4.2.23 on 2025-07-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0003_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
