# Generated by Django 4.2.23 on 2025-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0004_quiz_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
