# Generated by Django 4.2.23 on 2025-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0005_alter_question_correct_answer_alter_quiz_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='feedback',
            field=models.TextField(blank=True, help_text='Instructor feedback for this answer.', null=True),
        ),
        migrations.AddField(
            model_name='studentquizsubmission',
            name='feedback',
            field=models.TextField(blank=True, help_text='Overall feedback for the submission from instructor.', null=True),
        ),
        migrations.AddField(
            model_name='studentquizsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when grading was completed.', null=True),
        ),
        migrations.AddField(
            model_name='studentquizsubmission',
            name='status',
            field=models.CharField(choices=[('ungraded', 'Ungraded'), ('grading', 'Grading'), ('graded', 'Graded'), ('released', 'Released')], default='ungraded', help_text='Grading status of the submission.', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='points',
            field=models.IntegerField(help_text='Points awarded for this answer (0 to question.points).'),
        ),
        migrations.AlterField(
            model_name='studentquizsubmission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of awarded points for all answers, capped at quiz total_points.', max_digits=5, null=True),
        ),
    ]
