# Generated by Django 4.2.23 on 2025-08-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizroom', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='The order of this chunk in the video sequence')),
                ('chunk_path', models.CharField(help_text='Path to the chunk in storage', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField(help_text='Size of the chunk in bytes')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this chunk has been merged into the final video')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chunks', to='quizroom.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['quiz', 'student', 'is_processed'], name='quizroom_vi_quiz_id_762e97_idx')],
                'unique_together': {('quiz', 'student', 'sequence_number')},
            },
        ),
    ]
